service: aws-api-lambda-starter-template
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-2
  profile: eddie-personal
  memorySize: 128

functions:
  getGreetings:
    handler: src/handlers/getGreetings.main
    events:
      - httpApi:
          path: /greetings
          method: get
